# Generated by Django 2.0.2 on 2018-02-04 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_universidad', models.CharField(max_length=80)),
                ('acronimo_universidad', models.CharField(max_length=10, unique=True)),
                ('contacto', models.PositiveIntegerField(unique=True, verbose_name='Contacto')),
                ('pagina_web', models.URLField(unique=True, verbose_name='Página Web')),
            ],
            options={
                'verbose_name': 'Universidad',
                'verbose_name_plural': 'Universidades',
                'ordering': ['id'],
            },
        ),
    ]
