# Generated by Django 2.0.2 on 2018-02-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='contacto',
            field=models.PositiveIntegerField(blank=True, unique=True, verbose_name='Contacto'),
        ),
    ]
