# Generated by Django 2.0.2 on 2018-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_auto_20180204_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='pagina_web',
            field=models.URLField(blank=True, unique=True, verbose_name='Página Web'),
        ),
    ]
