# Generated by Django 2.0.2 on 2018-02-04 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0003_auto_20180204_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='universidad',
            name='contacto',
            field=models.PositiveIntegerField(unique=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='universidad',
            name='pagina_web',
            field=models.URLField(unique=True, verbose_name='Página Web'),
        ),
    ]
