# Generated by Django 2.0.2 on 2018-02-04 23:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0004_auto_20180204_1713'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_facultad', models.CharField(max_length=80)),
                ('pagina_web', models.URLField(unique=True, verbose_name='Página Web')),
                ('id_universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='principal.Universidad')),
            ],
            options={
                'verbose_name': 'Facultad',
                'verbose_name_plural': 'Facultades',
                'ordering': ['id'],
            },
        ),
    ]
