# Generated by Django 2.0.2 on 2018-02-04 23:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0005_facultad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='facultad',
            old_name='id_universidad',
            new_name='universidad',
        ),
    ]
