# Generated by Django 2.0.2 on 2018-02-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0006_auto_20180204_1751'),
    ]

    operations = [
        migrations.AddField(
            model_name='facultad',
            name='contacto',
            field=models.PositiveIntegerField(default=22351035, unique=True, verbose_name='Contacto'),
            preserve_default=False,
        ),
    ]
